export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Dashboard } from './Dashboard'
export { default as ListTukang } from './List'
export { default as Detail } from './Detail' 
export { default as Chat } from './Chat'
export { default as Order } from './Order' 
export { default as Submit } from './Submit'